### ISSUE TITLE
Create a logout button

### ISSUE THREAD

**Issue by felipe-clark** [ece1778-2020/MAX#15]
Currently there is no way to log out of the app! A logout button should be added to the settings screen.

Definition of done:
- A button to log out must be added to the settings screen. After pressing this button users should be brought back to the login screen, where they can either create a new account or login again with a pre-existing account.

**Comment by michellegasto** [comment]
![Slide3](https://user-images.githubusercontent.com/60204003/77231304-613b3200-6b70-11ea-96bf-3dcd1babfc60.jpeg)
