### ISSUE TITLE
Transition colors smoothly during session

### ISSUE THREAD

**Issue by felipe-clark** [ece1778-2020/MAX#23]

**Comment by michellegasto** [comment]
Becoming lighter green when within 5bps of the lower limit and darker green when within 5 bps of the upper limit.

![Slide6](https://user-images.githubusercontent.com/60204003/77195022-57a1c380-6ab7-11ea-9f79-760bd85d646c.jpeg)
![Slide7](https://user-images.githubusercontent.com/60204003/77195025-583a5a00-6ab7-11ea-9a64-874bf1612790.jpeg)
![Slide8](https://user-images.githubusercontent.com/60204003/77195027-583a5a00-6ab7-11ea-9110-d74712374c28.jpeg)
