### ISSUE TITLE
Exercise progression 

### ISSUE THREAD

**Issue by michellegasto** [ece1778-2020/MAX#26]
Would we be able to make the exercise progression be like the "weekly time in target range" reminder?

These were my ideas for when to give a progressing reminder:

- If the “time in target range” goal is met twice, then the app will suggest to increase this target by 15mins/week to a max of 120min/week (I can include more instructions under the info page so users won’t keep changing that target time)

- If after a month of using the app the average number of days is still not 3x/week, then the app will suggest to exercise 1 extra day per week till 3x/week is met.

I will keep working on this concept and how it will look as a reminder.

**Comment by michellegasto** [comment]
First progression target: 90 min in target HR range per week

- If in a span of 1 month, user averages less than 15 min in target HR range per week, prompt user with (first-time prompt/subsequent prompt): "Think about setting your "Exercise goal" in the User Settings page to 15 minutes in target HR range per week"/ "Keep aiming to exercise for 15 minutes in target HR range per week"

- If in a span of 1 month, user averages 15 min in target HR range per week, prompt user with "Think about setting your "Exercise goal" in the User Settings page to 90 minutes in target HR range per week"/ "Keep aiming to exercise for 30 minutes in target HR range per week"

- If in a span of 1 month, user averages 30 min in target HR range per week, prompt user with "Think about setting your "Exercise goal" in the User Settings page to 45 minutes in target HR range per week"/ "Keep aiming to exercise for 45 minutes in target HR range per week"

- If in a span of 1 month, user averages 45 min in target HR range per week, prompt user with "Think about setting your "Exercise goal" in the User Settings page to 60 minutes in target HR range per week"/ "Keep aiming to exercise for 60 minutes in target HR range per week"

- If in a span of 1 month, user averages 60 min in target HR range per week, prompt user with "Think about setting your "Exercise goal" in the User Settings page to 75 minutes in target HR range per week"/ "Keep aiming to exercise for 75 minutes in target HR range per week"

- If in a span of 1 month, user averages 75 min in target HR range per week, prompt user with "Think about setting your "Exercise goal" in the User Settings page to 90 minutes in target HR range per week"/ "Keep aiming to exercise for 90 minutes in target HR range per week"

**Comment by felipe-clark** [comment]
Minimum number of sessions in a month: 4 && at least 90 minutes in the target HR zone in the averaged -> prompting to increase + 15min

Remind the user to catch up if the user doesn't meet the new goal.

**Comment by michellegasto** [comment]
If doing well: "Think about increasing your "Exercise goal" in the User Settings page by 15 minutes"

**Comment by michellegasto** [comment]
Second progression target: Exercising 3 days/week

If in a span of 2 months, user averages less than 3 days/week: "Consider progressing to at least 3 days of exercise per week"
